### ISSUE TITLE
Script Error when upgrading Bob's Inserters with Nanobots

### ISSUE THREAD

**Issue by Nipahu** [Nexela/Nanobots#101] opened 2019-10-26 23:23 UTC
When an upgrade planner is used to upgrade Bob's yellow to red inserters the Nanobot script reports the following error: https://imgur.com/R7vXHal

**Comment by mnoreke** [comment] 2019-11-02 16:52
This is probably related to [https://github.com/Nexela/Nanobots/issues/95](url)

**Comment by pocghamp** [comment] 2020-02-14 16:37
Had the same issue with Express inserters (still same error, says red inserter). It did upgrade a couple of them but not all. When placing the blueprint directly with express inserters there is no problem.

**Comment by Nexela** [comment] 2020-09-21 00:47
Duplicate of #95

**Closed by Nexela** 2020-09-21 00:47 UTC
Labels: duplicate
