### ISSUE TITLE
Nanobots broken in version 0.15.14

### ISSUE THREAD

**Issue by jforr** [Nexela/Nanobots#54] opened 2017-05-26 13:58 UTC
I'm not expert enough to say why, but I get a repeatable crash anytime I place a ghost down and wait for nanobots to build.

**Comment by Nexela** [comment] 2017-05-26 14:05
Factorio is broken in 0.15.14

Waiting for an official dev response before making any changes.

**Comment by DaveSharman** [comment] 2017-05-26 16:32
You also get the same crash when sending out the termite nanobots to clear trees.  But I expect this is the same issue as above.

**Comment by DaveSharman** [comment] 2017-05-26 16:32
BTW, they should totally incorporate this into the base game.  This mod is simply AWESOME!!!

**Comment by Nexela** [comment] 2017-05-26 17:05
Thanks I totally agree, And yes related. Will be fixed in the next Factorio release.

**Closed by Nexela** 2017-05-26 17:05 UTC

**Comment by DaveSharman** [comment] 2017-05-26 18:19
Confirmed to be working as intended in 15.15.  It no longer crashes.
